platform :ios, '13.0'

def capacitor_pods
  use_frameworks!

  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  # TODO: Necessary?
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'

  pod 'LogRocket', '1.26.7'
end

target 'Plugin' do
  capacitor_pods
end

target 'PluginTests' do
  capacitor_pods
end
